llm:
  service: openai
  model: qwen3-max
  openai_api_key:  
  openai_base_url: https://dashscope.aliyuncs.com/compatible-mode/v1

rag:
  documents_dirs:
    path_list:
      - raw_data_path_1
      - raw_data_path_2
    name_list:
      - rag_name_1
      - rag_name_2
    description_list:
      - description for rag 1
      - description for rag 2
  embedding: Qwen/Qwen3-Embedding-0.6B
  use_storage: False