name: testbed
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - python=3.11.10=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.7
      - aiosignal==1.3.1
      - aiosmtpd==1.4.6
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - asgiref==3.8.1
      - atpublic==5.0
      - attrs==24.2.0
      - bcrypt==4.2.1
      - black==24.10.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - docutils==0.21.2
      - frozenlist==1.5.0
      - geoip2==4.8.1
      - h11==0.14.0
      - idna==3.10
      - jinja2==3.1.4
      - markupsafe==3.0.2
      - maxminddb==2.6.2
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - numpy==2.1.3
      - outcome==1.3.0.post0
      - packaging==24.2
      - pathspec==0.12.1
      - pillow==11.0.0
      - platformdirs==4.3.6
      - propcache==0.2.0
      - pycparser==2.22
      - pylibmc==1.6.3
      - pymemcache==4.0.0
      - pysocks==1.7.1
      - pywatchman==2.0.0
      - pyyaml==6.0.2
      - redis==5.2.0
      - requests==2.32.3
      - selenium==4.26.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sqlparse==0.5.2
      - tblib==3.0.0
      - trio==0.27.0
      - trio-websocket==0.11.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - websocket-client==1.8.0
      - wsproto==1.2.0
      - yarl==1.18.0
prefix: /opt/miniconda3/envs/testbed
