name: testbed
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_0
  - aiobotocore=2.15.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.10=py310h89163eb_0
  - aioitertools=0.12.0=pyhd8ed1ab_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - antlr-python-runtime=4.11.1=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asciitree=0.3.3=py_2
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - backports.zoneinfo=0.2.1=py310hff52083_9
  - beautifulsoup4=4.12.3=pyha770c72_0
  - blosc=1.21.6=hef167b5_0
  - boto3=1.35.23=pyhd8ed1ab_0
  - botocore=1.35.23=pyge310_1234567_0
  - bottleneck=1.4.2=py310hf462985_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py310hf71b8c6_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.2=heb4867d_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cartopy=0.24.0=py310h5eaa309_0
  - cdat_info=8.2.1=pyhd8ed1ab_2
  - cdms2=3.1.5=py310h366d46e_22
  - cdtime=3.1.4=py310h7a088e3_13
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cf-units=3.2.0=py310hf462985_6
  - cffi=1.17.1=py310h8deb56e_0
  - cfgrib=0.9.14.1=pyhd8ed1ab_0
  - cfgv=3.3.1=pyhd8ed1ab_0
  - cftime=1.6.4=py310hf462985_1
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.3.0=py310h3788b33_2
  - coverage=7.6.4=py310h89163eb_0
  - curl=8.10.1=hbbe4b11_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=1.0.0=py310ha75aee5_1
  - distarray=2.12.2=pyh050c7b8_4
  - distlib=0.3.9=pyhd8ed1ab_0
  - distributed=2024.10.0=pyhd8ed1ab_0
  - docopt-ng=0.9.0=pyhd8ed1ab_0
  - eccodes=2.38.0=h8bb6dbc_0
  - esmf=8.6.1=nompi_h4441c20_3
  - esmpy=8.6.1=pyhc1e730c_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - execnet=2.1.1=pyhd8ed1ab_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - filelock=3.16.1=pyhd8ed1ab_0
  - findlibs=0.0.5=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_0
  - flexparser=0.3.1=pyhd8ed1ab_0
  - flox=0.9.12=pyhd8ed1ab_0
  - fonttools=4.54.1=py310h89163eb_1
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.12.1=h267a509_2
  - freexl=2.0.0=h743c826_0
  - frozenlist=1.5.0=py310ha75aee5_0
  - fsspec=2024.10.0=pyhff2d567_0
  - future=1.0.0=pyhd8ed1ab_0
  - g2clib=1.9.0=ha770c72_1
  - geos=3.13.0=h5888daf_0
  - geotiff=1.7.3=h77b800c_3
  - giflib=5.2.2=hd590300_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5netcdf=1.4.0=pyhd8ed1ab_0
  - h5py=3.12.1=nompi_py310h60e0fe6_102
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - hypothesis=6.115.5=pyha770c72_0
  - icu=75.1=he02047a_0
  - identify=2.6.1=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - iris=3.10.0=pyha770c72_1
  - jasper=4.2.4=h536e39c_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py310h3788b33_0
  - krb5=1.21.3=h659f571_0
  - lazy-object-proxy=1.10.0=py310h2372a71_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.4=hfca40fe_0
  - libblas=3.9.0=25_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=25_linux64_openblas
  - libcdms=3.1.2=h0cec689_129
  - libcf=1.0.3=py310h1588dd5_117
  - libcurl=8.10.1=hbbe4b11_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgdal-core=3.9.2=hd5b9bfb_7
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglu=9.0.0=ha6d2627_1004
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=25_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnetcdf=4.9.2=nompi_h135f659_114
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libpng=1.6.44=hadc24fc_0
  - librttopo=1.1.0=h97f6797_17
  - libspatialite=5.1.0=h1b4f908_11
  - libsqlite=3.47.0=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=he137b08_1
  - libudunits2=2.2.28=h40f5838_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libxslt=1.1.39=h76b75d6_0
  - libzip=1.11.1=hf83b1b0_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.43.0=py310h1a6248f_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lxml=5.3.0=py310h6ee67d5_1
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - markupsafe=3.0.2=py310h89163eb_0
  - matplotlib-base=3.9.2=py310h68603db_1
  - minizip=4.0.7=h401b404_0
  - msgpack-python=1.1.0=py310h3788b33_0
  - multidict=6.1.0=py310h89163eb_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nc-time-axis=1.4.1=pyhd8ed1ab_0
  - nceplibs-g2c=1.9.0=ha39ef1c_1
  - ncurses=6.5=he02047a_1
  - netcdf-fortran=4.6.1=nompi_h22f9119_106
  - netcdf4=1.7.1=nompi_py310h9f0ad05_102
  - nodeenv=1.9.1=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.60.0=py310h5dc88bb_0
  - numcodecs=0.13.1=py310h5eaa309_0
  - numexpr=2.10.1=py310hdb6e06b_103
  - numpy_groupies=0.11.2=pyhd8ed1ab_0
  - openblas=0.3.28=pthreads_hbcdf1e8_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.2=hb9d3cd8_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.44=hba22ea6_2
  - pillow=11.0.0=py310hfeaa1f3_0
  - pint=0.24.3=pyhd8ed1ab_0
  - pip=24.2=pyh8b19718_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - pre-commit=4.0.1=pyha770c72_0
  - proj=9.5.0=h12925eb_0
  - propcache=0.2.0=py310ha75aee5_2
  - pseudonetcdf=3.4.0=pyhd8ed1ab_0
  - psutil=6.0.0=py310ha75aee5_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyhd8ed1ab_0
  - pydap=3.5=pyhd8ed1ab_0
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pyproj=3.7.0=py310h2e9f774_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest-cov=5.0.0=pyhd8ed1ab_0
  - pytest-env=1.1.5=pyhd8ed1ab_0
  - pytest-xdist=3.6.1=pyhd8ed1ab_0
  - python=3.10.15=h4a871b0_2_cpython
  - python-eccodes=2.37.0=py310hf462985_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py310ha75aee5_1
  - python_abi=3.10=5_cp310
  - pyyaml=6.0.2=py310ha75aee5_1
  - qhull=2020.2=h434a139_5
  - rasterio=1.4.1=py310hf6c6cbe_0
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rpds-py=0.20.0=py310h505e2c1_1
  - s3transfer=0.10.3=pyhd8ed1ab_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - shapely=2.0.6=py310had3dfd6_2
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=ha2e4443_0
  - snuggs=1.4.7=pyhd8ed1ab_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sparse=0.15.4=pyh267e887_1
  - sqlite=3.47.0=h9eae976_0
  - statsmodels=0.14.4=py310hf462985_0
  - tblib=3.0.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - toolz=1.0.0=pyhd8ed1ab_0
  - tornado=6.4.1=py310ha75aee5_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=hc8b5060_0
  - udunits2=2.2.28=h40f5838_3
  - ukkonen=1.0.1=py310h3788b33_5
  - unicodedata2=15.1.0=py310ha75aee5_1
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - virtualenv=20.27.0=pyhd8ed1ab_0
  - webob=1.8.8=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - wrapt=1.16.0=py310ha75aee5_1
  - xerces-c=3.2.5=h988505b_2
  - xorg-libx11=1.8.10=h4f16b4b_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xxhash=0.8.2=hd590300_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.16.0=py310ha75aee5_0
  - zarr=2.18.3=pyhd8ed1ab_0
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py310ha39cb0e_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - dask==2022.8.1
      - numbagg==0.8.2
      - numpy==1.23.0
      - packaging==23.1
      - pandas==1.5.3
      - pytest==7.4.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - scipy==1.11.1
      - setuptools==68.0.0
prefix: /opt/miniconda3/envs/testbed
