name: testbed
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - accessible-pygments=0.0.5=pyhd8ed1ab_1
  - adwaita-icon-theme=47.0=unix_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - alsa-lib=1.2.13=hb9d3cd8_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - attr=2.5.1=h166bdaf_1
  - attrs=25.1.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.3=pyha770c72_0
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h1ea3ea9_openblas
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.18.2=h3394656_1
  - cairocffi=1.7.1=pyhd8ed1ab_1
  - certifi=2025.1.31=py311h06a4308_0
  - cffi=1.17.1=py311h1fdaa30_1
  - cfgv=3.3.1=pyhd8ed1ab_1
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorspacious=1.1.2=pyhecae5ae_1
  - comm=0.2.2=pyhd8ed1ab_1
  - coverage=7.6.9=py311h5eee18b_0
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distlib=0.3.9=pyhd8ed1ab_1
  - docutils=0.21.2=pyhd8ed1ab_1
  - elfutils=0.192=h7f4e02f_1
  - epoxy=1.5.10=h166bdaf_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - execnet=2.1.1=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h5888daf_0
  - filelock=3.17.0=pyhd8ed1ab_0
  - flake8=7.1.2=pyhd8ed1ab_0
  - flake8-docstrings=1.7.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gettext=0.23.1=h5888daf_0
  - gettext-tools=0.23.1=h5888daf_0
  - glib=2.82.2=h07242d1_1
  - glib-tools=2.82.2=h4833e2c_1
  - gnutls=3.8.9=h5746830_0
  - graphite2=1.3.13=h59595ed_1003
  - graphviz=12.2.1=h5ae0cbf_1
  - gst-plugins-base=1.24.7=h0a52356_0
  - gstreamer=1.24.7=hf3bb09a_0
  - gtk3=3.24.43=h021d004_3
  - gtk4=4.14.1=hb98262c_0
  - gts=0.7.6=h977cf35_4
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=10.3.0=h76408a6_0
  - hicolor-icon-theme=0.17=ha770c72_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - identify=2.6.8=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.32.0=pyh907856f_0
  - ipywidgets=8.1.5=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libarchive=3.7.7=h4585015_3
  - libasprintf=0.23.1=h8e693c7_0
  - libasprintf-devel=0.23.1=h8e693c7_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp19.1=19.1.7=default_hb5137d0_1
  - libclang13=19.1.7=default_h9c6a7e4_1
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.12.1=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_0
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgd=2.3.3=h6f5c62b_11
  - libgettextpo=0.23.1=h5888daf_0
  - libgettextpo-devel=0.23.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgirepository=1.82.0=h0dcfedc_0
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h767d61c_2
  - libgpg-error=1.51=hbd13f7d_1
  - libgraphene=1.10.8=hc02c970_0
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - libllvm19=19.1.7=ha7bfdaf_1
  - liblzma=5.6.4=hb9d3cd8_0
  - libmicrohttpd=1.0.1=hbc5bc17_1
  - libmpdec=4.0.0=h4bc722e_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.4=h27ae623_0
  - librsvg=2.58.4=h49af25d_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.49.1=hee588c1_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsystemd0=257.3=h3dc2cb9_0
  - libtasn1=4.20.0=hb9d3cd8_0
  - libtiff=4.7.0=hd9ff511_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.8.0=hc4a0caf_0
  - libxml2=2.13.6=h8d12d68_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - markupsafe=3.0.2=py311h5eee18b_0
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mesalib=24.3.4=h0b126fc_1
  - mistune=3.1.2=pyhd8ed1ab_0
  - mpg123=1.32.9=hc50e24c_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=h266115a_4
  - mysql-libs=9.0.1=he0572af_4
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.9.1=h7ab15ed_0
  - nodeenv=1.9.1=pyhd8ed1ab_1
  - nspr=4.36=h5888daf_0
  - nss=3.108=h159eef7_0
  - numexpr=2.10.1=py311hd28fd6d_0
  - numpydoc=1.8.0=pyhd8ed1ab_1
  - openblas=0.3.29=pthreads_h6ec200e_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.4.1=h7b32b05_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pandas=2.2.3=py311h6a678d5_0
  - pandoc=3.6.3=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.1=h861ebed_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py311h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pluggy=1.5.0=pyhd8ed1ab_1
  - ply=3.11=pyhd8ed1ab_3
  - pre-commit=4.1.0=pyha770c72_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=5.9.0=py311h5eee18b_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyh415d2e4_2
  - pycairo=1.23.0=py311hd1222b9_0
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pydata-sphinx-theme=0.16.1=pyhd8ed1ab_0
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pygobject=3.50.0=py311hba7ce5e_1
  - pyqt=5.15.10=py311h6a678d5_1
  - pyqt5-sip=12.13.0=py311h5eee18b_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.3.4=pyhd8ed1ab_1
  - pytest-cov=6.0.0=pyhd8ed1ab_1
  - pytest-rerunfailures=15.0=pyhd8ed1ab_1
  - pytest-timeout=2.3.1=pyhd8ed1ab_2
  - pytest-xdist=3.6.1=pyhd8ed1ab_1
  - python=3.11.11=h9e4cc4f_1_cpython
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=26.2.0=py311h6a678d5_0
  - qt-main=5.15.15=hc3cb62f_2
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - roman-numerals-py=3.1.0=pyhd8ed1ab_0
  - rpds-py=0.22.3=py311h4aa5aa6_0
  - setuptools_scm=8.2.0=hd8ed1ab_0
  - sip=6.7.12=py311h6a678d5_1
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sphinx=8.2.1=pyhd8ed1ab_0
  - sphinx-copybutton=0.5.2=pyhd8ed1ab_1
  - sphinx-design=0.6.1=pyhd8ed1ab_2
  - sphinx-gallery=0.19.0=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py311h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - tzdata=2025a=h78e105d_0
  - ukkonen=1.0.1=py311hdb19cb5_1
  - unicodedata2=15.1.0=py311h5eee18b_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - virtualenv=20.29.2=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.45.1=py311h06a4308_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_1
  - wxpython=4.2.2=py311h356f471_6
  - wxwidgets=3.2.6=h1605dd1_2
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.11=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py311h2c38b39_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - contourpy==1.1.0
      - cycler==0.11.0
      - deprecation==2.1.0
      - fonttools==4.42.1
      - ghostscript==0.7
      - kiwisolver==1.4.5
      - lxml==5.3.1
      - numpy==1.25.2
      - packaging==23.1
      - pikepdf==8.4.1
      - pillow==10.0.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - setuptools==68.1.2
      - setuptools-scm==7.1.0
      - six==1.16.0
      - typing-extensions==4.7.1
prefix: /opt/miniconda3/envs/testbed
