name: testbed
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - python=3.9.20=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024b=h04d1e81_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - astroid==2.7.3
      - attrs==19.3.0
      - black==21.8b0
      - certifi==2024.8.30
      - cfgv==3.4.0
      - charset-normalizer==3.4.0
      - cli-ui==0.10.3
      - click==8.1.7
      - colorama==0.4.6
      - coverage==5.5
      - coveralls==3.3.1
      - distlib==0.3.9
      - docopt==0.6.2
      - execnet==2.1.1
      - filelock==3.16.1
      - flake8==3.9.2
      - gprof2dot==2024.6.6
      - identify==2.6.1
      - idna==3.10
      - iniconfig==2.0.0
      - isort==5.9.3
      - lazy-object-proxy==1.10.0
      - mccabe==0.6.1
      - mypy==0.910
      - mypy-extensions==0.4.4
      - nodeenv==1.9.1
      - packaging==24.1
      - pathspec==0.12.1
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pre-commit==2.21.0
      - py==1.11.0
      - py-cpuinfo==9.0.0
      - pycodestyle==2.7.0
      - pyenchant==3.2.2
      - pyflakes==2.3.1
      - pytest==6.2.5
      - pytest-benchmark==3.4.1
      - pytest-cov==2.12.1
      - pytest-forked==1.6.0
      - pytest-profiling==1.7.0
      - pytest-xdist==2.5.0
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - schema==0.7.7
      - six==1.16.0
      - tabulate==0.8.10
      - tbump==6.3.2
      - toml==0.10.2
      - tomli==1.2.3
      - tomlkit==0.13.2
      - types-pkg-resources==0.1.3
      - types-toml==0.1.5
      - typing-extensions==4.12.2
      - unidecode==1.3.8
      - urllib3==2.2.3
      - virtualenv==20.27.0
      - wrapt==1.12.1
prefix: /opt/miniconda3/envs/testbed
