name: testbed
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=openblas
  - bottleneck=1.4.2=py39ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.9.24=h06a4308_0
  - contourpy=1.0.5=py39hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - cython=3.0.10=py39h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - exceptiongroup=1.2.0=py39h06a4308_0
  - expat=2.6.3=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py39h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - joblib=1.4.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.9.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.0=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.6.2=py39h06a4308_0
  - matplotlib-base=3.6.2=py39h945d387_0
  - mysql=8.4.0=h29a9f33_1
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.8.4=py39hd2a5715_1
  - numpy=1.19.2=py39hc896f84_1
  - numpy-base=1.19.2=py39h21a3de8_1
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.1=py39h06a4308_0
  - pandas=1.4.4=py39h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.0.0=py39hfdbf927_0
  - pip=24.2=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - ply=3.11=py39h06a4308_0
  - pyparsing=3.2.0=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pytest=7.4.4=py39h06a4308_0
  - python=3.9.20=he870216_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - pytz=2024.1=py39h06a4308_0
  - qt-main=5.15.2=hb6262e9_11
  - readline=8.2=h5eee18b_0
  - scipy=1.5.2=py39hf56f3a7_0
  - setuptools=75.1.0=py39h06a4308_0
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - threadpoolctl=3.5.0=py39h2f386ee_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py39h06a4308_0
  - tornado=6.4.1=py39h5eee18b_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py39h5eee18b_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
prefix: /opt/miniconda3/envs/testbed
