name: citest

on:
  push:
    branches:
      - main
      - "release/**"
    paths-ignore:
      - "setup.*"
      - "requirements.txt"
      - "requirements/*"
      - "README.md"
      - ".github/workflows/lint.yaml"
      - ".github/workflows/publish.yaml"

  pull_request:
    paths-ignore:
      - "setup.*"
      - "requirements.txt"
      - "requirements/*"
      - "README.md"
      - ".github/workflows/lint.yaml"
      - ".github/workflows/publish.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittest:
    # The type of runner that the job will run on
    runs-on: self-hosted
    timeout-minutes: 60
    environment: testci
    steps:
    - uses: actions/checkout@v4

    # Add a step to check if it's a fork and set an environment variable
    - name: Check if PR is from a fork
      run: echo "IS_FORKED_PR=${{ github.event.pull_request.head.repo.fork }}" >> $GITHUB_ENV

    - name: Update pip
      run: pip install --upgrade pip

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install -r requirements.txt

    - name: Install DeepResearch Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install -r requirements/research.txt

    - name: Install Code Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install -r requirements/code.txt

    - name: Run tests
      shell: bash
      run: bash .dev_scripts/dockerci.sh
